# Generated by Django 5.0.7 on 2025-11-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_panel_layout_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('id_pm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('id_proyecto', models.IntegerField()),
                ('id_usuario_asignado', models.IntegerField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('prioridad', models.CharField(max_length=10)),
                ('progreso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiempoTarea',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('id_tarea', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'tiempo_tareas',
                'managed': False,
            },
        ),
    ]
