# Generated by Django 5.0.7 on 2025-11-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_proyecto_tarea_tiempotarea'),
    ]

    # La tabla 'reportes' ya existe en la base de datos; esta migración es un no-op.
    operations = []
