# Generated by Django 5.0.7 on 2025-11-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('id_usuario', models.IntegerField()),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('items', models.JSONField(blank=True, default=list)),
                ('secciones', models.JSONField(blank=True, default=list)),
                ('nota', models.TextField(blank=True, null=True)),
                ('formato', models.JSONField(blank=True, default=dict)),
                ('nombre_archivo', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteSnapshot',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('id_usuario', models.IntegerField()),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('items', models.JSONField(blank=True, default=list)),
                ('secciones', models.JSONField(blank=True, default=list)),
                ('nota', models.TextField(blank=True, null=True)),
                ('formato', models.JSONField(blank=True, default=dict)),
                ('nombre_archivo', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte (snapshot)',
                'verbose_name_plural': 'Reportes (snapshots)',
                'db_table': 'reportes_snapshots',
            },
        ),
    ]
