# Generated by Django 5.0.7 on 2025-11-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id_kpi', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo', models.CharField(choices=[('Financiero', 'Financiero'), ('Operacional', 'Operacional'), ('Cliente', 'Cliente'), ('Marketing', 'Marketing')], max_length=20)),
                ('id_proyecto', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'db_table': 'kpis',
                'managed': False,
            },
        ),
    ]
