# Generated by Django 5.0.7 on 2025-11-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_user_format_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150, null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
