# Generated by Django 5.0.7 on 2025-11-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_image_base64'),
        ('accounts', '0006_alter_usuario_options'),
    ]

    operations = [
    ]
